# Generated by Django 3.1.6 on 2021-03-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('time_day', models.CharField(max_length=255)),
                ('tip_cash', models.IntegerField()),
                ('tip_tran', models.IntegerField()),
                ('tip_total', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='List_ID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='ID_bank',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ID_card',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ID_job',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_number',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
