# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-18 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpos', '0002_auto_20210318_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ID_bank',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ID_card',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ID_job',
            field=models.CharField(max_length=50),
        ),
    ]
